/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.os.rh.telas;

import br.os.rh.pontoprofessores.PontoProfessores;
import br.os.rh.pontoprofessores.PontoProfessoresDAO;
import br.os.rh.util.Ativo;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 'Pedro
 */
public class TelaJustificaPontoNaoMarcao extends javax.swing.JDialog {

    private static PontoProfessores pp;
    private boolean mEntrada = false, mSaida = false;

    public static void chamaTela(PontoProfessores pp) {
        TelaJustificaPontoNaoMarcao.pp = pp;
        new TelaJustificaPontoNaoMarcao().setVisible(true);
    }

    /**
     * Creates new form TelaJustificaPontoNaoMarcao
     */
    public TelaJustificaPontoNaoMarcao() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        lblPonto.setText(String.valueOf(pp.getId()));
        if (pp.isAtestado()) {

            cbAtestado.setSelected(true);
            cbAtestado.setEnabled(false);
            mEntrada = true;
            mSaida = true;
            tfJustEntrada1.setText(pp.getJustEntrada());
            edtHoraEntrada.setEnabled(false);
            tfJustEntrada1.setEnabled(false);
            tfJustSaida.setText(pp.getJustSaida());
            tfJustSaida.setEnabled(false);
            edtHoraSaida.setEnabled(false);

        } else {
            if (pp.getHoraEntrada() != null) {
                edtHoraEntrada.setText(String.valueOf(pp.getHoraEntrada()));
                tfJustEntrada1.setText(pp.getJustEntrada());
                edtHoraEntrada.setEnabled(false);
                tfJustEntrada1.setEnabled(false);
                if (pp.getHoraSaida() == null) {
                    edtHoraEntrada.setEnabled(true);
                    tfJustEntrada1.setEnabled(true);
                }

                

            } else {
                mEntrada = true;
            }

            if (pp.getHoraSaida() != null) {
                tfJustSaida.setText(pp.getJustSaida());
                tfJustSaida.setEnabled(false);
                edtHoraSaida.setText(String.valueOf(pp.getHoraSaida()));
                edtHoraSaida.setEnabled(false);
            } else {
                mSaida = true;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btJustificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtHoraSaida = new javax.swing.JFormattedTextField();
        edtHoraEntrada = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfJustSaida = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfJustEntrada1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        cbAtestado = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        lblPonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btJustificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/os/rh/imagens/confi.gif"))); // NOI18N
        btJustificar.setText("Justificar");
        btJustificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJustificarActionPerformed(evt);
            }
        });
        jPanel5.add(btJustificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabel1.setText("Hora Saída:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel2.setText("Hora Entrada:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        try {
            edtHoraSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(edtHoraSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, -1));

        try {
            edtHoraEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(edtHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, -1));

        tfJustSaida.setColumns(20);
        tfJustSaida.setRows(5);
        jScrollPane1.setViewportView(tfJustSaida);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 340, 60));

        tfJustEntrada1.setColumns(20);
        tfJustEntrada1.setRows(5);
        jScrollPane2.setViewportView(tfJustEntrada1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 340, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/os/rh/imagens/SA.png"))); // NOI18N
        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 80, -1));

        cbAtestado.setBackground(new java.awt.Color(255, 255, 255));
        cbAtestado.setText("Atestado");
        jPanel5.add(cbAtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 450, 290));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("JUSTIFICAR/VISUALIZAR PONTO DE NÚMERO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        lblPonto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPonto.setForeground(new java.awt.Color(255, 0, 0));
        lblPonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPonto.setText("jLabel3");
        jPanel1.add(lblPonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJustificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJustificarActionPerformed
        // TODO add your handling code here:
        if (cbAtestado.isSelected()) {
            if (JOptionPane.showConfirmDialog(rootPane, "Confirma Atestado?", "Confirma",
                    JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE
            ) == JOptionPane.NO_OPTION) {
                cbAtestado.setSelected(false);
            } else {
                edtHoraEntrada.setText("");
                edtHoraSaida.setText("");
            }
        }
        if (edtHoraEntrada.getText().equals("  :  :  ") && cbAtestado.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Informe a hora de entrada");
        } else if (edtHoraSaida.getText().equals("  :  :  ") && cbAtestado.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Informe a hora de Saída");
        } else {
            if (cbAtestado.isSelected() == false) {
                //só seta hora se o professor não estiver de atestado
                try {
                    DateFormat formatter = new SimpleDateFormat("HH:mm:ss");
                    pp.setHoraEntrada(formatter.parse(edtHoraEntrada.getText()));
                    pp.setHoraSaida(formatter.parse(edtHoraSaida.getText()));
                } catch (Exception e) {

                }
            }
            pp.setJustEntrada(tfJustEntrada1.getText());
            pp.setJustSaida(tfJustSaida.getText());
            pp.setAtestado(cbAtestado.isSelected());

            if (mEntrada) {
                if (cbAtestado.isSelected()) {
                    pp.setJustEntrada(pp.getJustEntrada() + "\n(ATESTADO) ");
                }
                pp.setJustEntrada(pp.getJustEntrada() + "\n Adicionado Por: " + Ativo.getUsuario().getNome()
                        + "\n Data: " + new Date());
            }
            if (mSaida) {
                if (cbAtestado.isSelected()) {
                    pp.setJustSaida(pp.getJustSaida() + "\n(ATESTADO) ");
                }
                pp.setJustSaida(pp.getJustSaida() + "\n Adicionado Por: " + Ativo.getUsuario().getNome()
                        + "\n Data: " + new Date());
            }

            PontoProfessoresDAO ppDAO = new PontoProfessoresDAO();
            ppDAO.salvar(pp);
            JOptionPane.showMessageDialog(rootPane, "Justificativa adicionada com sucesso!");
            dispose();

        }

    }//GEN-LAST:event_btJustificarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJustificaPontoNaoMarcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJustificaPontoNaoMarcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJustificaPontoNaoMarcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJustificaPontoNaoMarcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJustificaPontoNaoMarcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJustificar;
    private javax.swing.JCheckBox cbAtestado;
    private javax.swing.JFormattedTextField edtHoraEntrada;
    private javax.swing.JFormattedTextField edtHoraSaida;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPonto;
    private javax.swing.JTextArea tfJustEntrada1;
    private javax.swing.JTextArea tfJustSaida;
    // End of variables declaration//GEN-END:variables
}
