/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.os.rh.telas;

import br.edu.evento.Evento;
import br.edu.evento.EventoDAO;
import br.edu.eventoitem.EventoItem;
import br.edu.eventoitem.EventoItemDAO;
import br.os.rh.util.ConnectionFactory;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author 'Pedro
 */
public class TelaRelatorioPontoEvento extends javax.swing.JDialog {

    /**
     * Creates new form TelaRelatorioPontoEvento
     */
    public TelaRelatorioPontoEvento() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        preencheEvento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbItens = new javax.swing.JComboBox();
        cbEvento = new javax.swing.JComboBox();
        btImprimir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ítem:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Evento:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cbItens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbItens.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Selecione -" }));
        cbItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbItensMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbItensMousePressed(evt);
            }
        });
        cbItens.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItensItemStateChanged(evt);
            }
        });
        cbItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItensActionPerformed(evt);
            }
        });
        jPanel5.add(cbItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 340, -1));

        cbEvento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Selecione -" }));
        cbEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEventoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbEventoMousePressed(evt);
            }
        });
        cbEvento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEventoItemStateChanged(evt);
            }
        });
        cbEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEventoActionPerformed(evt);
            }
        });
        jPanel5.add(cbEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 340, -1));

        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/os/rh/imagens/imprimir2.png"))); // NOI18N
        btImprimir.setToolTipText("Sair");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        jPanel5.add(btImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/os/rh/imagens/SA.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel5.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 430, 150));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RELATÓRIO PONTO EVENTO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbItensMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbItensMouseClicked

    private void cbItensMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbItensMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbItensMousePressed

    private void cbItensItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItensItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbItensItemStateChanged

    private void cbItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItensActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbItensActionPerformed

    private void cbEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEventoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbEventoMouseClicked

    private void cbEventoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEventoMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbEventoMousePressed

    private void cbEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEventoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbEventoItemStateChanged

    private void cbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventoActionPerformed
        // TODO add your handling code here:
        preencheItensEvento();
    }//GEN-LAST:event_cbEventoActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
        JasperReport pathjrxml;
        HashMap parametros = new HashMap();
        String sql = "", texto = "", item="";

        if (cbEvento.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Período!");
        }

        if (cbItens.getSelectedIndex() != 0) {
            sql += String.valueOf(((EventoItem)cbItens.getSelectedItem()).getId());
            texto+=((Evento)cbEvento.getSelectedItem()).getDescricao();
            item+=((EventoItem)cbItens.getSelectedItem()).getDescricao();
            parametros.put("sql", sql);
            parametros.put("texto", texto);
            parametros.put("item", item);

            Connection connection = new ConnectionFactory().getConnection();
            try {
                JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Relatório", true);
                viewer.setSize(1000, 600);
                viewer.setLocationRelativeTo(null);
                viewer.setModal(true);
                pathjrxml = JasperCompileManager.compileReport("relatorios/RelPontoEvento.jrxml");
                JasperPrint printReport = JasperFillManager.fillReport(pathjrxml, parametros,
                    connection);
                JasperViewer jv = new JasperViewer(printReport, false);
                viewer.getContentPane().add(jv.getContentPane());
                viewer.setVisible(true);
                //JasperExportManager.exportReportToPdfFile(printReport, "src/relatorios/RelAcervo.pdf");

                //jv.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_btImprimirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    public void preencheEvento() {
        cbEvento.removeAllItems();
        EventoDAO edao = new EventoDAO();
        cbEvento.addItem("- Selecione -");
        for (Evento evt : edao.listar()) {
            cbEvento.addItem(evt);
        }
    }

    public void preencheItensEvento() {
        if (cbEvento.getSelectedIndex() > 0) {
            cbItens.removeAllItems();
            EventoItemDAO edao = new EventoItemDAO();
            cbItens.addItem("- Selecione -");
            for (EventoItem evt : edao.listarItensEvento((Evento) cbEvento.getSelectedItem())) {
                cbItens.addItem(evt);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPontoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPontoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPontoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPontoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioPontoEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox cbEvento;
    private javax.swing.JComboBox cbItens;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
